#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.11"
# dependencies = [
#   "markdown-it-py==3.0.0",
# ]
# ///

import argparse
import html
import re
from pathlib import Path

from markdown_it import MarkdownIt


STYLE = """\
    :root {
      color-scheme: light;
      --bg: #f7f4ee;
      --paper: #fffdf9;
      --ink: #17212b;
      --muted: #51606f;
      --accent: #9c6644;
      --line: #dfd4c7;
    }

    * {
      box-sizing: border-box;
    }

    body {
      margin: 0;
      font-family: Georgia, "Times New Roman", serif;
      background:
        radial-gradient(circle at top right, rgba(156, 102, 68, 0.09), transparent 30%),
        linear-gradient(180deg, #fbf8f3 0%, var(--bg) 100%);
      color: var(--ink);
      line-height: 1.65;
    }

    main {
      max-width: 860px;
      margin: 0 auto;
      padding: 48px 20px 64px;
    }

    article {
      background: var(--paper);
      border: 1px solid var(--line);
      border-radius: 18px;
      padding: 36px 28px;
      box-shadow: 0 18px 50px rgba(23, 33, 43, 0.06);
    }

    h1, h2 {
      line-height: 1.2;
      margin-top: 0;
    }

    h1 {
      font-size: clamp(2rem, 4vw, 2.8rem);
      margin-bottom: 0.4rem;
    }

    h2 {
      font-size: 1.35rem;
      margin-top: 2rem;
      margin-bottom: 0.75rem;
      color: var(--accent);
    }

    p, li {
      font-size: 1rem;
    }

    .updated {
      color: var(--muted);
      margin-top: 0;
      margin-bottom: 1.5rem;
    }

    ul {
      padding-left: 1.4rem;
    }

    a {
      color: var(--accent);
    }

    @media (max-width: 640px) {
      main {
        padding: 24px 12px 40px;
      }

      article {
        padding: 24px 18px;
        border-radius: 14px;
      }
    }
"""


def page_title(markdown_text: str) -> str:
    md = MarkdownIt("commonmark")
    tokens = md.parse(markdown_text)
    for index, token in enumerate(tokens):
        if token.type == "heading_open" and token.tag == "h1":
            inline = tokens[index + 1]
            return inline.content.strip()
    return "Privacy Policy"


def render_markdown(markdown_text: str) -> str:
    md = MarkdownIt("commonmark")
    rendered = md.render(markdown_text).strip()
    return re.sub(r"<p>Last updated:(.*?)</p>", r'<p class="updated">Last updated:\1</p>', rendered, count=1, flags=re.DOTALL)


def build_html(title: str, content: str, generated_from: str) -> str:
    return f"""<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{html.escape(title)}</title>
  <style>
{STYLE}
  </style>
</head>
<body>
  <main>
    <article>
      <!-- Generated from {html.escape(generated_from)}. Do not edit this file directly. -->
      {content}
    </article>
  </main>
</body>
</html>
"""


def build_privacy_policy_html(markdown_text: str) -> str:
    return build_html(
        title=page_title(markdown_text),
        content=render_markdown(markdown_text),
        generated_from="PRIVACY_POLICY.md",
    )


def build_index_html() -> str:
    return build_html(
        title="Meow Printer Docs",
        content="""
      <h1>Meow Printer Docs</h1>
      <p>Available documents:</p>
      <p><a href="./privacy-policy.html">Privacy Policy</a></p>
""".strip(),
        generated_from="scripts/generate_docs_html.py",
    )


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate the static docs HTML pages from the privacy policy Markdown.",
    )
    parser.add_argument("source", nargs="?", default="PRIVACY_POLICY.md")
    parser.add_argument("target", nargs="?", default="docs/privacy-policy.html")
    parser.add_argument(
        "--index-target",
        default="docs/index.html",
        help="Output path for the generated docs index page.",
    )
    args = parser.parse_args()

    source = Path(args.source)
    target = Path(args.target)
    index_target = Path(args.index_target)
    html_text = build_privacy_policy_html(source.read_text(encoding="utf-8"))
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(html_text, encoding="utf-8")
    index_target.parent.mkdir(parents=True, exist_ok=True)
    index_target.write_text(build_index_html(), encoding="utf-8")


if __name__ == "__main__":
    main()
